-- 회원테이블
CREATE TABLE members
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email               VARCHAR(254)    NOT NULL,
    email_verified_at   TIMESTAMPTZ     NULL,
    nickname            VARCHAR(30)     NOT NULL,
    profile_image_url   VARCHAR(2048)   NULL,
    status              VARCHAR(20)     NOT NULL,
    created_at          TIMESTAMPTZ     NOT NULL,
    updated_at          TIMESTAMPTZ     NOT NULL,
    last_login_at       TIMESTAMPTZ     NULL,
    withdrawn_at        TIMESTAMPTZ     NULL,

    CONSTRAINT pk_members
    PRIMARY KEY (id),

    CONSTRAINT ck_members_status
    CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);

-- 이메일 중복 방지 (회원테이블)
CREATE UNIQUE INDEX uq_members_email
    ON  members (LOWER(email));

-- 회원 자격증명 테이블
CREATE TABLE member_credentials
(
    member_id           BIGINT         NOT NULL,
    password_hash       VARCHAR(255)    NOT NULL,
    password_changed_at TIMESTAMPTZ     NOT NULL,
    created_at          TIMESTAMPTZ     NOT NULL,

    CONSTRAINT pk_member_credentials
    PRIMARY KEY (member_id),

    CONSTRAINT fk_member_credentials_member_id
        FOREIGN KEY (member_id)
            REFERENCES members (id)
            ON DELETE CASCADE
);

-- 소셜 로그인 테이블
CREATE TABLE social_accounts
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id                   BIGINT          NOT NULL,
    provider                    VARCHAR(20)     NOT NULL,
    provider_user_id            VARCHAR(255)    NOT NULL,
    provider_email              VARCHAR(254)    NULL,
    provider_display_name       VARCHAR(100)    NULL,
    provider_profile_image_url  VARCHAR(2048)   NULL,
    created_at                  TIMESTAMPTZ     NOT NULL,
    updated_at                  TIMESTAMPTZ     NOT NULL,
    last_synced_at              TIMESTAMPTZ     NULL,

    CONSTRAINT pk_social_accounts
    PRIMARY KEY (id),

    CONSTRAINT fk_social_accounts_member_id
        FOREIGN KEY (member_id)
            REFERENCES members (id)
            ON DELETE CASCADE,

    CONSTRAINT uq_social_accounts_provider_provider_user_id
    UNIQUE (provider, provider_user_id),

    CONSTRAINT uq_social_accounts_member_id_provider
    UNIQUE (member_id, provider),

    CONSTRAINT ck_social_accounts_provider
    CHECK (provider IN ('GOOGLE', 'KAKAO', 'FACEBOOK'))
);

-- 채팅방 테이블
CREATE TABLE chat_rooms
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type            VARCHAR(20)     NOT NULL,
    name            VARCHAR(30)     NULL,
    direct_key      VARCHAR(50)     NULL,
    last_message_at TIMESTAMPTZ     NULL,
    created_at      TIMESTAMPTZ     NOT NULL,
    updated_at      TIMESTAMPTZ     NOT NULL,
    deleted_at      TIMESTAMPTZ     NULL,

    CONSTRAINT pk_chat_rooms
    PRIMARY KEY (id),

    CONSTRAINT uq_chat_rooms_direct_key
    UNIQUE (direct_key),

    CONSTRAINT ck_chat_rooms_type
    CHECK (type IN ('DIRECT', 'GROUP')),

    CONSTRAINT ck_chat_rooms_type_fields
    CHECK (
        (type = 'DIRECT' AND direct_key IS NOT NULL AND name IS NULL)
        OR
        (type = 'GROUP' AND direct_key IS NULL AND name IS NOT NULL)
    )
);

-- 첨부파일 테이블
CREATE TABLE attachments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uploader_id     BIGINT          NOT NULL,
    original_name   VARCHAR(255)    NOT NULL,
    content_type    VARCHAR(255)    NOT NULL,
    size_bytes      BIGINT          NOT NULL,
    storage_key     VARCHAR(1024)   NOT NULL,
    status          VARCHAR(20)     NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL,
    activated_at    TIMESTAMPTZ     NULL,
    deleted_at      TIMESTAMPTZ     NULL,

    CONSTRAINT pk_attachments
    PRIMARY KEY (id),

    CONSTRAINT fk_attachments_uploader_id
        FOREIGN KEY (uploader_id)
            REFERENCES members (id)
            ON DELETE RESTRICT,

    CONSTRAINT uq_attachments_storage_key
    UNIQUE (storage_key),

    CONSTRAINT ck_attachments_size_bytes
    CHECK (size_bytes > 0),

    CONSTRAINT ck_attachments_status
    CHECK (status IN ('PENDING', 'ACTIVE', 'DELETED'))
);

-- 오랜된 파일 정리를 위한 인덱스 (첨부파일)
CREATE INDEX idx_attachments_status_created_at
    ON attachments (status, created_at);

-- 채팅 메시지 테이블
CREATE TABLE chat_messages
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    room_id             BIGINT      NOT NULL,
    sender_id           BIGINT      NULL,
    client_message_id   UUID        NULL,
    type                VARCHAR(20) NOT NULL,
    content             TEXT        NULL,
    attachment_id       BIGINT      NULL,
    created_at          TIMESTAMPTZ NOT NULL,
    edited_at           TIMESTAMPTZ NULL,
    deleted_at          TIMESTAMPTZ NULL,

    CONSTRAINT pk_chat_messages
    PRIMARY KEY (id),

    CONSTRAINT fk_chat_messages_room_id
        FOREIGN KEY (room_id)
            REFERENCES chat_rooms (id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_chat_messages_sender_id
            FOREIGN KEY (sender_id)
                REFERENCES members (id)
                ON DELETE RESTRICT,

    CONSTRAINT fk_chat_messages_attachment_id
        FOREIGN KEY (attachment_id)
            REFERENCES attachments (id)
            ON DELETE RESTRICT,

    CONSTRAINT uq_chat_messages_sender_id_client_message_id
    UNIQUE (sender_id, client_message_id),

    CONSTRAINT uq_chat_messages_attachment_id
    UNIQUE (attachment_id),

    CONSTRAINT ck_chat_messages_type
    CHECK (type IN ('TEXT', 'IMAGE', 'FILE', 'SYSTEM')),

    CONSTRAINT ck_chat_messages_type_fields
    CHECK (
        (
            type = 'TEXT'
            AND sender_id IS NOT NULL
            AND client_message_id IS NOT NULL
            AND content IS NOT NULL
            AND attachment_id IS NULL
        )
        OR
        (
            type IN ('IMAGE', 'FILE')
            AND sender_id IS NOT NULL
            AND client_message_id IS NOT NULL
            AND attachment_id IS NOT NULL
        )
        OR
        (
            type = 'SYSTEM'
            AND sender_id IS NULL
            AND client_message_id IS NULL
            AND content IS NOT NULL
            AND attachment_id IS NULL
        )
    )
);

-- id 기준 메시지 목록 조회 인덱스 (채팅 메시지 테이블)
CREATE INDEX idx_chat_messages_room_id_id_desc
    ON chat_messages (room_id, id DESC);

-- 채팅방 멤버 테이블
CREATE TABLE chat_room_members
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    room_id                 BIGINT      NOT NULL,
    member_id               BIGINT      NOT NULL,
    role                    VARCHAR(20) NOT NULL,
    last_read_message_id    BIGINT      NULL,
    joined_at               TIMESTAMPTZ NOT NULL,
    left_at                 TIMESTAMPTZ NULL,

    CONSTRAINT pk_chat_room_members
    PRIMARY KEY (id),

    CONSTRAINT fk_chat_room_members_room_id
        FOREIGN KEY (room_id)
            REFERENCES chat_rooms (id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_chat_room_members_member_id
        FOREIGN KEY (member_id)
            REFERENCES members (id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_chat_room_members_last_read_message_id
        FOREIGN KEY (last_read_message_id)
            REFERENCES chat_messages (id)
            ON DELETE RESTRICT,

    CONSTRAINT uq_chat_room_members_room_id_member_id
    UNIQUE (room_id, member_id),

    CONSTRAINT ck_chat_room_members_role
    CHECK (role IN ('OWNER', 'MEMBER'))
);

CREATE INDEX idx_chat_room_members_member_id_left_at
    ON chat_room_members (member_id, left_at);

CREATE INDEX idx_chat_room_members_room_id_left_at
    ON chat_room_members (room_id, left_at);

CREATE UNIQUE INDEX uq_chat_room_members_active_owner
    ON chat_room_members (room_id)
    WHERE role = 'OWNER'
        AND left_at IS NULL;